# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Automatic Cell Tuner
copyright: "2025"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/V-Marco/ACT
  path_to_book: docs
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true

sphinx:
  config:
    add_function_parentheses: true
    add_module_names: false
    suppress_warnings: ["etoc.toctree"]
    napoleon_numpy_docstring: true
    autoclass_content: init
  extra_extensions:
    - numpydoc
    - sphinx.ext.autodoc
    - sphinx.ext.napoleon
    - sphinx.ext.viewcode
    - sphinx.ext.intersphinx